version: "3.7"

services:
  # * Portainer container * #
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: -H unix:///var/run/docker.sock
    networks:
      - t2_proxy
    environment:
      - TZ=$TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $CFGDIR/portainer/data:/data # Change to local directory if you want to save/transfer config locally
    labels:
      - "traefik.enable=true"
      ## note: HTTP Routers Section
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.$DOMAINNAME`)"
      - "traefik.http.routers.portainer-rtr.tls=true"

      ## note: Middlewares Section
      # ! To enable Authentication wanted, comment out ONLY one of the below lines.
      ## note: No Authentication
      - "traefik.http.routers.portainer-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## note: Basic Authentication
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      ## todo: Google OAuth Authentication
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## todo: Authelia Authentication
      # - "traefik.http.routers.portainer-rtr.middlewares=chain-authelia@file" # Authelia

      ## note: HTTP Services Section
      - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
