version: "3.7"

services:
  #  * Dozzle Container *  #
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      DOZZLE_LEVEL: $DZL_LEVEL
      DOZZLE_TAILSIZE: $DZL_TAILSIZE
      ## note: The below line limits logs displayed to containers with this label
      DOZZLE_FILTER: $DZL_FILTER
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      ## note: HTTP Routers Section
      - "traefik.http.routers.dozzle-rtr.entrypoints=https"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME`)"
      - "traefik.http.routers.dozzle-rtr.tls=true"
      ## note: Middlewares Section
      # ! To enable Authentication wanted, comment out ONLY one of the below lines.
      ## note: No Authentication
      # - "traefik.http.routers.dozzle-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## note: Basic Authentication
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      ## note: Google OAuth Authentication
      # - "traefik.http.routers.dozzle-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## note: Authelia Authentication
      # - "traefik.http.routers.dozzle-rtr.middlewares=chain-authelia@file" # Authelia
      ## note: HTTP Services Section
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"
