version: "3.7"

services:
  #  * Jellyfin Container *  #
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - t2_proxy
    environment:
      # ! to find a user's UID or GID in *nix,
      # ! use the "id" command.
      - PUID=$PUID # ! ex: id -u <username>
      - PGID=$PGID # ! ex: id -g <username>
      - TZ=$TZ
      - UMASK_SET=022 # note: optional
    volumes:
      - $CFGDIR/jellyfin/data:/config
      - /dev/shm:/ram_transcode
      - $DATDIR/jellyfin/tvseries:/data/tvshows
      - $DATDIR/jellyfin/movies:/data/movies
      - $DATDIR/jellyfin/books:/data/books
    devices:
      - /dev/dri:/dev/dri # note: for hardware transcoding
    security_opt:
      - no-new-privileges:true
    ports:
      - 8096:8096
      ##- 8920:8920     # note: optional
    labels:
      - "traefik.enable=true"
      ## note: HTTP Routers Section
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`media.$DOMAINNAME`)"
      - "traefik.http.routers.jellyfin-rtr.tls=true"

      ## note: Middlewares Section
      # ! To enable Authentication wanted, comment out ONLY one of the below lines.
      ## note: No Authentication
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      ## note: Basic Authentication
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-basic-auth@file"
      ## note: Google OAuth Authentication
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-oauth@file"
      ## note: Authelia Authentication
      # - "traefik.http.routers.jellyfin-rtr.middlewares=chain-authelia@file"

      ## note: HTTP Services Section
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
