version: '3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - $CFGDIR/authelia/config:/config
    networks:
      - frontend-net
    #ports:
    #  - 9091:9091
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.example.me`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.example.me'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=$TZ
    healthcheck:
      disable: true

networks:
  frontend-net:
    external: true