###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  johndoe:
    displayname: "John Doe"
    # Password is Authelia
    password: "Password Hash Goes Here"
    email: john.doe@example.me
    groups:
      - admins
      - dev
