version: "3.7"

services:
  # * qBittorrent Container * #
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $CFGDIR/qbtorrent:/config
      - $DATDIR/Torrents:/downloads
    environment:
      # ! to find a user's UID or GID in *nix,
      # ! use the "id" command.
      - PUID=$PUID # ! ex: id -u <username>
      - PGID=$PGID # ! ex: id -g <username>
      - UMASK_SET: 002
      - WEBUI_PORT: 8168
    labels:
      - "traefik.enable=true"
      ## note: HTTP Routers Section
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME`)"
      - "traefik.http.routers.qbittorrent-rtr.tls=true"

      ## note: Middlewares Section
      # ! To enable Authentication wanted, comment out ONLY one of the below lines.
      ## note: No Authentication
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-no-auth@file"
      ## note: Basic Authentication
      # - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-basic-auth@file"
      ## note: Google OAuth Authentication
      # - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"
      ## note: Authelia Authentication
      # - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-authelia@file"

      ## note: HTTP Services Section
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8168"
