version: "3.7"

services:
  #  * Ghost Container *  #
  ghost:
    image: ghost
    container_name: ghost
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - t2_proxy
    volumes:
      - $CFGDIR/ghost:/var/lib/ghost/content
    environment:
      # ! to find a user's UID or GID in *nix,
      # ! use the "id" command.
      - PUID=$PUID # ! ex: id -u <username>
      - PGID=$PGID # ! ex: id -g <username>
      - TZ=$TZ
    labels:
      - "traefik.enable=true"

      ## note: HTTP Routers Section
      - "traefik.http.routers.ghost-rtr.entrypoints=https"
      - "traefik.http.routers.ghost-rtr.rule=Host(`blog.$DOMAINNAME`)"
      - "traefik.http.routers.ghost-rtr.tls=true"

      ## note: Middlewares Section
      # ! To enable Authentication wanted, comment out ONLY one of the below lines.
      ## note: No Authentication
      - "traefik.http.routers.ghost-rtr.middlewares=chain-no-auth@file" # No Authentication
      ## note: Basic Authentication
      # - "traefik.http.routers.ghost-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      ## note: Google OAuth Authentication
      # - "traefik.http.routers.ghost-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## note: Authelia Authentication
      # - "traefik.http.routers.ghost-rtr.middlewares=chain-authelia@file" # Authelia

      ## note: HTTP Services Section
      - "traefik.http.routers.ghost-rtr.service=ghost-svc"
      - "traefik.http.services.ghost-svc.loadbalancer.server.port=2368"
